### ISSUE TITLE
Chrome version update

### ISSUE THREAD

**Issue by csutorasr** [alexeagle/ngcontainer#10]
Please update chrome to the latest version. [PR comment Link](https://github.com/angular/angular/pull/23288#discussion_r180850520)

The base image has not the latest version and it is not compatible with the latest chrome driver.

**Comment by alexeagle** [comment]
Angular is updated this morning to ngcontainer 0.2.0 which includes
https://github.com/alexeagle/ngcontainer/tree/0.1.1
you'll see the latest commit there sets `$CHROMEDRIVER_VERSION_ARG`
so that the version of chrome driver matches the version of chrome.

If we simply update chrome in this docker container but leave the chromedriver version floating, we will break again next time the two get out of sync.

**Comment by csutorasr** [comment]
The current behavior on aio e2e test is upgrading the driver and run tests (before that Travis updates chrome to the latest version). If we changed that it would break Travis; if we don't then it won't work with CircleCI. Maybe different test arguments will be needed until we change to CircleCI.

**Comment by alexeagle** [comment]
the right thing to do is for the container to provide versions of things that work together.
instead of upgrading the driver, can't that test always use the CHROMEDRIVER_VERSION_ARG variable?

**Comment by csutorasr** [comment]
It tests the current version, but before that it is upgrading it.

There are a lot of parts of the CI and yarn scripts that has to be changed as it is very Travis dependent.

**Comment by alexeagle** [comment]
Sorry, I don't follow if something still needs to change here. We could
update both Chrome and Chromedriver variable if that's the right thing to
do for all users of this container?
